version: 0.2

phases:
  install:
    commands:
      - echo "Installing PHP 8.1..."
      - sudo yum install -y php php-cli php-mbstring php-xml php-bcmath php-pdo php-mysqlnd unzip
      - php -v
  build:
    commands:
      - echo "Building the application..."
artifacts:
  files:
    - '**/*'
